#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/h.savarala/Documents/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/h.savarala/Desktop/dev/paisa"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/h.savarala/Desktop/dev/paisa/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=6.3.3"
export "FLUTTER_BUILD_NUMBER=633"
export "DART_DEFINES=RkxVVFRFUl9XRUJfQ0FOVkFTS0lUX1VSTD1odHRwczovL3d3dy5nc3RhdGljLmNvbS9mbHV0dGVyLWNhbnZhc2tpdC9lZGQ4NTQ2MTE2NDU3YmRmMWM1YmRmYjEzZWNiOTQ2M2QyYmI1ZWQ0Lw==,RkxVVFRFUl9BUFBfRkxBVk9SPWRldg=="
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/h.savarala/Desktop/dev/paisa/.dart_tool/package_config.json"
export "FLAVOR=dev"
